version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
#    networks:
#      - mongodb-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "myReplicaSet" ]

  mongoinit:
    image: "mongo"
    container_name: "mongodb_replSet_initializer"
    restart: "no"
    depends_on:
      - mongo
#    networks:
#      - mongodb-network
    command: >
      mongosh --host mongodb:27017 --eval "rs.initiate({
       _id: \"myReplicaSet\",
       members: [
         {_id: 0, host: \"mongodb\"}
       ]
      })"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
#    networks:
#      - mongodb-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example

volumes:
  data: {}

networks:
  default:
    name: mongodb-network
